### ISSUE TITLE
fresh install

### ISSUE THREAD

**Issue by werwercat** [Nexuist/CoinMarketCapAPI#14]
/root/coinapi/lib/CoinFactory.js:25
      "symbol": tds.eq(4).text().match(/\s([a-z]|[0-9])+\s/i)[0].trim().toLowerCase(),
                                                             ^

TypeError: Cannot read property '0' of null
    at CoinFactory.produce (/root/coinapi/lib/CoinFactory.js:25:62)
    at Object.<anonymous> (/root/coinapi/lib/CoinCrawler.js:30:33)
    at initialize.exports.each (/root/coinapi/node_modules/cheerio/lib/api/traversing.js:294:24)
    at Request._callback (/root/coinapi/lib/CoinCrawler.js:29:14)
    at Request.self.callback (/root/coinapi/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/coinapi/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)

**Comment by NarubyRiverlione** [comment]
See my comment in issue #12 and my solution in pull request #13

**Comment by Nexuist** [comment]
Should be fixed now.
